### ISSUE TITLE
[FEAT] experiment tracking by mlflow

### ISSUE THREAD

**Issue by twndus** [twndus/YelpRecommendation#9]
## Background
- After the initial implementation of the model, establish a process to track experiments using MLflow

## To do
- [x] logging metric
- [ ] setup sweep

**Comment by GangBean** [comment]
- MLflow requires another server instance to save metrics and handle the UI process.
- However, due to restricted server resources in the project, we opt to utilize **Weights and Biases** instead, as it offers free cloud resources.
